
import { Container, Typography } from '@mui/material'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'

import { useGlobalContext } from '../../state/context'



import styles from '../styles/Home.module.css'
import addproduct from './api/addproduct'




export default  function Home() {

  const { image ,data } = useGlobalContext()



  return (

    <>
   
      <Head>
        <title>Mihir Patel</title>
        <meta name="description" content="Generated by mihir patel" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/myLogo.jpeg" />

      </Head>
      <main >

        <div className={styles.bg}>
          <img height={500} width={500}  src='/iphone2.png' alt=''/>
        </div>
        <div className={`${styles.main} heading`}>
          <Container>

            <Typography variant='h3' className='heading' >{data.heading}</Typography>
            <Typography variant='h4'>{data.title}</Typography>
          </Container>
        </div>
      </main>
     
      <div className={styles.img} >
        <div className={styles.app}  >
          {image.map((e, i) => {
            return<Link href={`${e.href}${e.name}`} style={{textDecoration:'none',color:'black'}} key={i}>
               <div className={styles.imglist}  > 
  

             <Typography className={styles.shape} variant='h5'><p style={{fontSize:'1rem'}}>only</p>₹{e.price}</Typography>
             <img  className={styles.gear} height={200} width={150} loading='lazy' src={e.image} alt={e.price} />

              <Typography className={styles.typo} variant='h5'>Phone Case</Typography>
            </div>
            </Link>
          })}
        </div>
      </div>
    </>
  )
}